Node *head=new Node(10);
	// Node *temp1=new Node(20);
	// Node *temp2=new Node(30);
	// head->next=temp1;
	// temp1->next=temp2;
    // temp2->next = head;
    // traverse(head);
    // head = insertBegin(head, 5);
    // head = insertEnd(head, 40);
    // traverse(head);